// Generated by ts-to-zod
import { z } from 'zod'

const latexSchema = z.string()

export const arrowModeSchema = z.union([z.literal('NONE'), z.literal('POSITIVE'), z.literal('BOTH')])

export const grapherStateSchema = z.object({
  viewport: z.object({
    xmin: z.number(),
    ymin: z.number(),
    xmax: z.number(),
    ymax: z.number(),
  }),
  xAxisMinorSubdivisions: z.number().optional(),
  yAxisMinorSubdivisions: z.number().optional(),
  degreeMode: z.boolean().optional(),
  showGrid: z.boolean().optional(),
  showXAxis: z.boolean().optional(),
  showYAxis: z.boolean().optional(),
  xAxisNumbers: z.boolean().optional(),
  yAxisNumbers: z.boolean().optional(),
  polarNumbers: z.boolean().optional(),
  xAxisStep: z.number().optional(),
  yAxisStep: z.number().optional(),
  xAxisArrowMode: arrowModeSchema.optional(),
  yAxisArrowMode: arrowModeSchema.optional(),
  xAxisLabel: z.string().optional(),
  yAxisLabel: z.string().optional(),
  squareAxes: z.boolean().optional(),
  restrictGridToFirstQuadrant: z.boolean().optional(),
  polarMode: z.boolean().optional(),
  userLockedViewport: z.boolean().optional(),
})

const idSchema = z.string()

const baseItemStateSchema = z.object({
  id: idSchema,
  secret: z.boolean().optional(),
})

const baseNonFolderStateSchema = baseItemStateSchema.extend({
  folderId: idSchema.optional(),
})

export const lineStyleSchema = z.union([z.literal('SOLID'), z.literal('DASHED'), z.literal('DOTTED')])

export const pointStyleSchema = z.union([z.literal('POINT'), z.literal('OPEN'), z.literal('CROSS')])

export const dragModeSchema = z.union([
  z.literal('NONE'),
  z.literal('X'),
  z.literal('Y'),
  z.literal('XY'),
  z.literal('AUTO'),
])

export const labelSizeSchema = z.union([z.literal('SMALL'), z.literal('MEDIUM'), z.literal('LARGE'), latexSchema])

export const labelOrientationSchema = z.union([
  z.literal('default'),
  z.literal('center'),
  z.literal('center_auto'),
  z.literal('auto_center'),
  z.literal('above'),
  z.literal('above_left'),
  z.literal('above_right'),
  z.literal('above_auto'),
  z.literal('below'),
  z.literal('below_left'),
  z.literal('below_right'),
  z.literal('below_auto'),
  z.literal('left'),
  z.literal('auto_left'),
  z.literal('right'),
  z.literal('auto_right'),
])

export const domainSchema = z.object({
  min: latexSchema,
  max: latexSchema,
})

export const baseClickableSchema = z.object({
  enabled: z.boolean().optional(),
  description: z.string().optional(),
  latex: latexSchema.optional(),
})

const expressionStateWithoutColumnSchema = baseNonFolderStateSchema.extend({
  type: z.literal('expression'),
  showLabel: z.boolean().optional(),
  fill: z.boolean().optional(),
  fillOpacity: latexSchema.optional(),
  label: z.string().optional(),
  labelSize: labelSizeSchema.optional(),
  labelOrientation: labelOrientationSchema.optional(),
  labelAngle: latexSchema.optional(),
  suppressTextOutline: z.boolean().optional(),
  interactiveLabel: z.boolean().optional(),
  editableLabelMode: z.union([z.literal('MATH'), z.literal('TEXT')]).optional(),
  residualVariable: latexSchema.optional(),
  regressionParameters: z.record(z.number()).optional(),
  isLogModeRegression: z.boolean().optional(),
  displayEvaluationAsFraction: z.boolean().optional(),
  slider: z
    .object({
      hardMin: z.boolean().optional(),
      hardMax: z.boolean().optional(),
      animationPeriod: z.number().optional(),
      loopMode: z
        .union([
          z.literal('LOOP_FORWARD_REVERSE'),
          z.literal('LOOP_FORWARD'),
          z.literal('PLAY_ONCE'),
          z.literal('PLAY_INDEFINITELY'),
        ])
        .optional(),
      playDirection: z.union([z.literal(1), z.literal(-1)]).optional(),
      isPlaying: z.boolean().optional(),
      min: latexSchema.optional(),
      max: latexSchema.optional(),
      step: latexSchema.optional(),
    })
    .optional(),
  polarDomain: domainSchema.optional(),
  parametricDomain: domainSchema.optional(),
  domain: domainSchema.optional(),
  cdf: z
    .object({
      show: z.boolean(),
      min: latexSchema.optional(),
      max: latexSchema.optional(),
    })
    .optional(),
  vizProps: z
    .object({
      breadth: latexSchema.optional(),
      axisOffset: latexSchema.optional(),
      alignedAxis: z.union([z.literal('x'), z.literal('y')]).optional(),
      showBoxplotOutliers: z.boolean().optional(),
      dotplotXMode: z.union([z.literal('exact'), z.literal('binned')]).optional(),
      binAlignment: z.union([z.literal('left'), z.literal('center')]).optional(),
      histogramMode: z.union([z.literal('count'), z.literal('relative'), z.literal('density')]).optional(),
    })
    .optional(),
  clickableInfo: baseClickableSchema.optional(),
})

export const columnExpressionSharedSchema = z.object({
  color: z.string(),
  latex: latexSchema.optional(),
  hidden: z.boolean().optional(),
  points: z.boolean().optional(),
  lines: z.boolean().optional(),
  dragMode: dragModeSchema.optional(),
  lineStyle: lineStyleSchema.optional(),
  pointStyle: pointStyleSchema.optional(),
  colorLatex: latexSchema.optional(),
  lineOpacity: latexSchema.optional(),
  lineWidth: latexSchema.optional(),
  pointSize: latexSchema.optional(),
  pointOpacity: latexSchema.optional(),
})

export const imageStateSchema = baseNonFolderStateSchema.extend({
  type: z.literal('image'),
  image_url: z.string(),
  name: z.string().optional(),
  width: latexSchema.optional(),
  height: latexSchema.optional(),
  hidden: z.boolean().optional(),
  center: latexSchema.optional(),
  angle: latexSchema.optional(),
  opacity: latexSchema.optional(),
  foreground: z.boolean().optional(),
  draggable: z.boolean().optional(),
  clickableInfo: baseClickableSchema
    .and(
      z.object({
        hoveredImage: z.string().optional(),
        depressedImage: z.string().optional(),
      }),
    )
    .optional(),
})

export const tableColumnSchema = z
  .object({
    id: idSchema,
    values: z.array(latexSchema),
  })
  .and(columnExpressionSharedSchema)

export const tableStateSchema = baseNonFolderStateSchema.extend({
  type: z.literal('table'),
  columns: z.array(tableColumnSchema),
})

export const folderStateSchema = baseItemStateSchema.extend({
  type: z.literal('folder'),
  hidden: z.boolean().optional(),
  collapsed: z.boolean().optional(),
  title: z.string().optional(),
})

export const textStateSchema = baseNonFolderStateSchema.extend({
  type: z.literal('text'),
  text: z.string().optional(),
})

export const tickerSchema = z.object({
  handlerLatex: latexSchema.optional(),
  minStepLatex: latexSchema.optional(),
  open: z.boolean().optional(),
  playing: z.boolean().optional(),
})

export const expressionStateSchema = expressionStateWithoutColumnSchema.and(columnExpressionSharedSchema)

export const nonFolderStateSchema = z.union([
  expressionStateSchema,
  imageStateSchema,
  tableStateSchema,
  textStateSchema,
])

export const itemStateSchema = z.union([nonFolderStateSchema, folderStateSchema])

export const graphStateSchema = z.object({
  version: z.number(),
  randomSeed: z.string().optional(),
  graph: grapherStateSchema,
  expressions: z.object({
    list: z.array(itemStateSchema),
    ticker: tickerSchema.optional(),
  }),
})

export const graphStateJSONSchema = z
  .string()
  .transform((val, ctx) => {
    try {
      return JSON.parse(val)
    } catch (error) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: 'invalid json',
      })
      return z.never
    }
  })
  .pipe(graphStateSchema)
